apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-instance
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dagster.yaml: |
    run_launcher:
      module: dagster_graphql.launcher.k8s
      class: K8sRunLauncher
      config:

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_url: "postgresql://{{ .Values.postgresql.postgresqlUsername}}:{{ .Values.postgresql.postgresqlPassword	}}@{{ template "dagster.postgresql.fullname" . }}:{{ .Values.postgresql.service.port }}/postgres"

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_url: "postgresql://{{ .Values.postgresql.postgresqlUsername}}:{{ .Values.postgresql.postgresqlPassword	}}@{{ template "dagster.postgresql.fullname" . }}:{{ .Values.postgresql.service.port }}/postgres"